### PR TITLE
[Do not merge until MSAL 2.6] Using the new UIBehavior.None for applying the EditProfile policy

### PR DESCRIPTION
**Pull request by jmprieur**

### CODE REVIEW

**Comment by jmprieur** [comment]
Good job @jennyf19 
cc: @parakhj :)

**Comment by parakhj** [comment]
@jennyf19 does "NoPrompt" mean that the request is using prompt=none or no prompt parameter at all?

**Comment by jmprieur** [comment]
@parakhj, this means no prompt is sent at all.

**Comment by parakhj** [comment]
sweet!

**Pull request merged**
