### PR TITLE
Update to MSAL 4.45.0. Add Microsoft.IdentityModel.Abstractions reference.

### PR DESCRIPTION
**Pull request by pmaytak**

### CODE REVIEW

**Comment by jmprieur** [comment]
@bgavrilMS : as discussed, this is a breaking change for customers who are still on package.json
@pmaytak: how was the error? was it explicit enough ? Would you have known what to do if you were not aware of the new package?

Also: do we want to move this sample to package reference?

**Comment by pmaytak** [comment]
@jmprieur The exception is runtime, not compile time, but it's pretty straightforward.
```
FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Abstractions, Version=6.18.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

One benefit of keeping this project type is to catch behavior like this. But if this is legacy project type, maybe it's good to update to the latest and recommended.

**Comment by jmprieur** [comment]
Sounds good to me, @pmaytak 
Thanks!

@SameerK-MSFT @bgavrilMS : definitively a breaking change if that happens at runtime. We need to document it.

**Comment by bgavrilMS** [comment]
@pmaytak - did you upgrade MSAL manually by editing the packages.config file? I am surprised to see this behavior.

**Comment by pmaytak** [comment]
@bgavrilMS Hmm, that's a good point. I updated MSAL in packages.config and csproj manually. Let me try it via Nuget manager, maybe it'll auto download all dependencies.

**Comment by pmaytak** [comment]
@bgavrilMS @jmprieur When I updated the MSAL NuGet via package manager, the abstractions package was indeed automatically added. So I guess this is just a good learning, since some partners do in fact add MSAL DLLs directly, not via NuGet.

**Pull request merged**
